<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Rust.Localization</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Rust.FileSystem">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>rustds/RustDedicated_Data/Managed/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>