<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp-firstpass</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Rust.UI">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Unity">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Input">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Input.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>