<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Rust.World</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Rust.Data">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="LZ4">
      <HintPath>rustds/RustDedicated_Data/Managed/LZ4.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>