<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Facepunch.System</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Unity.Collections">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Burst.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>