<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.World">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.World.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Localization">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Rust.UI">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.UI.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Facepunch.Nexus">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Nexus.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Unity">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Global">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Global.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>rustds/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Clans">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Clans.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>rustds/RustDedicated_Data/Managed/UniTask.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>rustds/RustDedicated_Data/Managed/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="CurvedTextMeshPro">
      <HintPath>rustds/RustDedicated_Data/Managed/CurvedTextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Platform.Common">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Platform.Common.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Skeleton">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Skeleton.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.BurstCloth">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.BurstCloth.dll</HintPath>
    </Reference>
    <Reference Include="EZhex1991.EZSoftBone">
      <HintPath>rustds/RustDedicated_Data/Managed/EZhex1991.EZSoftBone.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="LeTai.TrueShadow">
      <HintPath>rustds/RustDedicated_Data/Managed/LeTai.TrueShadow.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Flexbox">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Flexbox.dll</HintPath>
    </Reference>
    <Reference Include="Wardddev.FlexibleColorPicker">
      <HintPath>rustds/RustDedicated_Data/Managed/Wardddev.FlexibleColorPicker.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Workshop">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Workshop.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Raknet">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Raknet.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="NewAssembly">
      <HintPath>rustds/RustDedicated_Data/Managed/NewAssembly.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Input">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Input.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnwrapBaker.Settings">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.UnwrapBaker.Settings.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.FileSystem">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="Ionic.Zip.Reduced">
      <HintPath>rustds/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll</HintPath>
    </Reference>
    <Reference Include="Cronos">
      <HintPath>rustds/RustDedicated_Data/Managed/Cronos.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Sqlite">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.RenderPipeline">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.RenderPipeline.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>rustds/RustDedicated_Data/Managed/System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>rustds/RustDedicated_Data/Managed/Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Rust.UI.Toolkit.DemoControls">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.UI.Toolkit.DemoControls.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="RTLTMPro">
      <HintPath>rustds/RustDedicated_Data/Managed/RTLTMPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Fleck">
      <HintPath>rustds/RustDedicated_Data/Managed/Fleck.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Rcon">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Rcon.dll</HintPath>
    </Reference>
    <Reference Include="ZString">
      <HintPath>rustds/RustDedicated_Data/Managed/ZString.dll</HintPath>
    </Reference>
    <Reference Include="Azure.Storage.Blobs">
      <HintPath>rustds/RustDedicated_Data/Managed/Azure.Storage.Blobs.dll</HintPath>
    </Reference>
    <Reference Include="Azure.Identity">
      <HintPath>rustds/RustDedicated_Data/Managed/Azure.Identity.dll</HintPath>
    </Reference>
    <Reference Include="Azure.Core">
      <HintPath>rustds/RustDedicated_Data/Managed/Azure.Core.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Ping">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Ping.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Harmony">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="UIEffect">
      <HintPath>rustds/RustDedicated_Data/Managed/UIEffect.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Clans.Local">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Clans.Local.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Platform">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Platform.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Demo">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.Demo.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>rustds/RustDedicated_Data/Managed/System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="TimeZoneConverter">
      <HintPath>rustds/RustDedicated_Data/Managed/TimeZoneConverter.dll</HintPath>
    </Reference>
    <Reference Include="LZ4">
      <HintPath>rustds/RustDedicated_Data/Managed/LZ4.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.SteamNetworking">
      <HintPath>rustds/RustDedicated_Data/Managed/Facepunch.SteamNetworking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="Rust.UI.Toolkit">
      <HintPath>rustds/RustDedicated_Data/Managed/Rust.UI.Toolkit.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>rustds/RustDedicated_Data/Managed/UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="BoomlagoonJSON">
      <HintPath>rustds/RustDedicated_Data/Managed/BoomlagoonJSON.dll</HintPath>
    </Reference>
    <Reference Include="Oxide.Core">
      <HintPath>rustds/RustDedicated_Data/Managed/Oxide.Core.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>rustds/RustDedicated_Data/Managed/Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>